name: pemrograman_mobile
description: "Expense Manager dengan Hive, GetX, dan Fitur Lengkap"
publish_to: 'none'
version: 1.0.0+1

# PERBAIKAN DI SINI: GANTI ':-' jadi ':'
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DATABASE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.1
  path_provider: ^2.1.1

  # STATE MANAGEMENT
  get: ^4.6.6

  # NOTIFIKASI
  flutter_local_notifications: ^17.0.0

  # KALENDER
  table_calendar: ^3.0.9

  # FORMAT ANGKA & TANGGAL
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # HIVE GENERATOR
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true